<a href="https://colab.research.google.com/github/Shaileshchaskar81/explore-python/blob/master/ShaileshAssignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
try :
  print('Diving by zero will raise Exception')
  a = 5/0
except ZeroDivisionError as e:
  print("----Exception caught : ", e)
  print('----Avoid Division by Zero')
except Exception as ex:
  print("Unknwon Exception caught : ", ex)
finally : 
  print('----------Notification - Exception caught and handled in except block')

Diving by zero will raise Exception
----Exception caught :  division by zero
----Avoid Division by Zero
----------Notification - Exception caught and handled in except block


In [24]:
subjects = ['Americans','Indians']
verbs = ['play', 'watch']
objects = ['Baseball', 'Cricket']

print('---------------Implementation 1--------------')
for i in subjects:
  for j in verbs:
    for k in objects:
      print(i+ ' ' + j + ' ' +k)

print('---------------Implementation 2 --------------')
output  = [i + ' ' + j + ' ' +k for i in subjects for j in verbs for k in objects]

for pr in output:
    print(pr)

---------------Implementation 1--------------
Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket
---------------Implementation 2 --------------
Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [25]:
import numpy as np
   
def showmatrix(mylist,col,inflag):
  mymatrix=[]
  for i in mylist:
    for j in range(col):  
      if inflag:
         mymatrix.append(i**j)
      else:
        power = col-1-j
        mymatrix.append(i**power)
  newmatrix=np.array(mymatrix)
  print(newmatrix.reshape(len(mylist),col))
    
mylist=[2,4,5,10]
col=4

incflag= True
decflag = False
print("------Increasing is True----")
showmatrix(mylist,col,incflag)
print("   ")
print("------Decreasing is True----")
showmatrix(mylist,col,decflag)

------Increasing is True---
[[   1    2    4    8]
 [   1    4   16   64]
 [   1    5   25  125]
 [   1   10  100 1000]]
   
------Decreasing is True---
[[   8    4    2    1]
 [  64   16    4    1]
 [ 125   25    5    1]
 [1000  100   10    1]]
